### ISSUE TITLE
Wrong instruction in README.md

### ISSUE THREAD

**Issue by kafeinnet** [LemonLDAPNG/lemonldap-ng-docker#11]
Hi,

In the README.md file, the following line has no sense and does not work.

```
sudo echo "127.0.0.1 auth.example.com manager.example.com test1.example.com test2.example.com" >> /etc/hosts
```

An unprivileged user needs sudo to append a line to /etc/hosts. He does not need sudo to echo this line. The correct instruction should be : 

```
echo "127.0.0.1 auth.example.com manager.example.com test1.example.com test2.example.com" | sudo tee -a /etc/hosts
```

\fab

**Comment by coudot** [comment]
Thanks for the notice!
