### ISSUE TITLE
Unable to start CentOS trunk container after a first run

### ISSUE THREAD

**Issue by coudot** [LemonLDAPNG/lemonldap-ng-docker#12]
Running the CentOS trunk container the first time works great. But after a stop, I am unable to start it again:
```
clement@ader-sfl:~$ docker start objective_montalcini
objective_montalcini
clement@ader-sfl:~$ docker logs objective_montalcini 
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
httpd (pid 10) already running
```

**Comment by coudot** [comment]
@tdemaret any idea on how to fix this?

**Comment by coudot** [comment]
Maybe @faust64 can have an idea?

**Comment by faust64** [comment]
From that error message, I'ld wild guess it has to do with httpd pid file already existing on your filesystem
Also, `httpd.conf` should be in `conf.d` -- it looks like the `ServerName` definition is added to a file httpd won't read.

Theoretical fix / pending further tests: faust64/lemonldap-ng-docker@303d29105c52323274ad1f4bb8836d8b03ff43f3

**Comment by coudot** [comment]
See PR #16

**Comment by coudot** [comment]
@faust64 your solution works well, thanks!
