### ISSUE TITLE
OpenIdConnect auth as Basic Auth

### ISSUE THREAD

**Issue by amouhzi** [LemonLDAPNG/lemonldap-ng-docker#20]
Hello,

When I use Lemonldap installed on a final server, openid connect login authentication works correctly. When I use Lemonldap supplied in a docker container, the following error is displayed:

Unable to get access_token

But when I pass the credentials using body's request, it works.

It seems that the headers are not transmitted to the manager or something similar.

Some applications used only headers to authenticate.

**Comment by coudot** [comment]
Do you use the container with Apache? If yes these lines need to be uncommented in portal-apache2.conf : 
```
        #RewriteCond %{HTTP:Authorization} .
        #RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Or use
```
CGIPassAuth on
```

**Comment by amouhzi** [comment]
Yes, I'm using the container with apache. And this solved my problem.

Thank you so much.
