### ISSUE TITLE
Update to 2.0.x

### ISSUE THREAD

**Issue by Neraud** [LemonLDAPNG/lemonldap-ng-docker#21]
Since #18, the current project only builds a v1.9 version of LemonLDAP.
Could you please update it to build a 2.0.x ?

**Comment by coudot** [comment]
Indeed, we need to do it.

Note that 2.0 dockerfiles are avaliable in docker-trunk/

**Comment by Neraud** [comment]
Oh indeed, I didn't see that folder (I was looking for a branch ...), thank you.

Could you please point me toward the Dokerfile closest to the one you'll use to build the official 2.x image ? I'm guessing the most recent one (Debian 10 + NGinx).

Do you have a rough ETA for the 2.X image ?
I'm not asking for an exact date of course, but knowing if it's a matter of days, weeks or months will change how I handle things on my end.

**Comment by GuiF007** [comment]
> Indeed, we need to do it.
> 
> Note that 2.0 dockerfiles are available in docker-trunk/

Thank you for the answer, but seems it does not work properly when I run the image : 

> Starting periodic command scheduler: cron.
> Starting anac(h)ronistic cron: anacron.
> Starting llng-fastcgi-server: llng-fastcgi-serverFastCGI daemon started (pid 34)
> .
> nginx: [emerg] open() "/etc/nginx/sites-enabled/test-nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62

**Comment by coudot** [comment]
Thanks to @guimard and @maxbes we now have a Docker image for LL::NG 2.0, you can get it here: https://hub.docker.com/r/coudot/lemonldap-ng/

**Comment by GuiF007** [comment]
Thank you very much @guimard, @maxbes and @coudot
