### ISSUE TITLE
Invalid command 'CGIPassAuth'

### ISSUE THREAD

**Issue by vdubus** [LemonLDAPNG/lemonldap-ng-docker#5]
Hello,

I use this project's Dockerfile as a base of my own project, and since version of lemonldap-ng 1.9.10, I get the following error:

```
lemonldap-ng                | AH00526: Syntax error on line 29 of /etc/apache2/sites-enabled/portal-apache2.conf:
lemonldap-ng                | Invalid command 'CGIPassAuth', perhaps misspelled or defined by a module not included in the server configuration
lemonldap-ng                | Action '-DFOREGROUND' failed.
lemonldap-ng                | The Apache error log may have more information.
lemonldap-ng exited with code 1
```

After comparing both 1.9.9 and 1.9.10 version of lemonldap-ng, I found that this error was caused by the line `CGIPassAuth on` which didn't exist in the 1.9.9 version.

```
    # Perl script
    <Files *.pl>
        SetHandler perl-script
        PerlResponseHandler ModPerl::Registry
	CGIPassAuth on
    </Files>
```

I was able to fix this error by writing the following line in my own Dockerfile:

```
RUN sed -i 's/CGIPassAuth on/#CGIPassAuth on/g' /etc/lemonldap-ng/portal-apache2.conf
```

**Comment by coudot** [comment]
Indeed CGIPassAuth is not available in this version of Apache. I will use your fix in the Dockerfile.

Thanks for the report.

**Comment by coudot** [comment]
Should be fixed. New docker images were uploaded.
