### ISSUE TITLE
Changing test domain to localhost

### ISSUE THREAD

**Issue by nippo** [LemonLDAPNG/lemonldap-ng-docker#8]
Hi,

I use container from https://hub.docker.com/r/coudot/lemonldap-ng/. I tried to changed the domain from example.com to localhost but if I can see the last connexions page, I still redirect to auth.localhost with login form...

Otherwise, LemonLDAP NG default config works with example.com behind nginx proxy...

Do you see what I don't do well?

Thanks!

**Comment by coudot** [comment]
localhost is not a domain but a full hostname, so it won't work. You can just edit your /etc/hosts if you need to test the docker image:
̀````
127.0.0.1 auth.example.com manager.example.com test1.example.com test2.example.com
̀````

**Comment by nippo** [comment]
OK, thanks! My purpose is to connect a Django apps with SAML. I succed with OneLogin but I think it's gone a be more difficult with LemonLDAP. I read this for now: http://elatov.github.io/2014/02/lemonldap-ng-ldap-saml-google-apps/...

If you have some advices, I'll take it!

**Comment by coudot** [comment]
SAML is not mandatory, you can directly have LL::NG support in Django, see https://pypi.python.org/pypi/django-lemonldap/2.0.0

**Comment by nippo** [comment]
Thanks, I'm going to test this app... I work with MIN and they want to use LemonLDAP NG SAML with ESRI Portal.. In theory, users will connect to my django app, then they will be abble to click on links to go to ESRI Portal apps with the session they've created in the django app... MIN do not want users to log on to the ESRI portal the first time...

**Comment by coudot** [comment]
Yes, you can authenticate on ESRI portal with SAML and on your Django application with SAML or HTTP headers. The important thing is that LL::NG is managing user authentication, it is the Identity Provider and the user can then connect to other applications without re-authenticating.

I close this issue as the original question was answered.

If you have question on LL::NG, use project mailing lists: https://lemonldap-ng.org/contact#mailing_lists
